var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,e){a!=Array.prototype&&a!=Object.prototype&&(a[c]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,c,e,f){if(c){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var b=a[f];b in e||(e[b]={});e=e[b]}a=a[a.length-1];f=e[a];c=c(f);c!=f&&null!=c&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function e(d){return d instanceof b?d:new b(function(a,b){a(d)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};c.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var f=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(d){f(d,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var a=0;a<d.length;++a){var b=d[a];delete d[a];try{b()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};c.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var b=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{d(a.resolve,a.reject)}catch(l){a.reject(l)}};b.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};b.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var d=null!=a;break a;case "function":d=!0;break a;default:d=!1}d?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};b.prototype.resolveToNonPromiseObj_=function(a){var d=
void 0;try{d=a.then}catch(l){this.reject_(l);return}"function"==typeof d?this.settleSameAsThenable_(d,a):this.fulfill_(a)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var g=new c;b.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};b.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(k){d.reject(k)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(m){f(m)}}:b}var e,f,h=new b(function(a,
b){e=a;f=b});this.callWhenSettled_(d(a,e),d(c,f));return h};b.prototype["catch"]=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?g.asyncExecute(d):this.onSettledCallbacks_.push(function(){g.asyncExecute(d)})};b.resolve=e;b.reject=function(a){return new b(function(b,d){d(a)})};b.race=function(a){return new b(function(b,
d){for(var c=$jscomp.makeIterator(a),f=c.next();!f.done;f=c.next())e(f.value).callWhenSettled_(b,d)})};b.all=function(a){var d=$jscomp.makeIterator(a),c=d.next();return c.done?e([]):new b(function(a,b){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,e(c.value).callWhenSettled_(f(g.length-1),b),c=d.next();while(!c.done)})};return b},"es6","es3");
$jscomp.executeAsyncGenerator=function(a){function c(c){return a.next(c)}function e(c){return a["throw"](c)}return new Promise(function(f,b){function g(a){a.done?f(a.value):Promise.resolve(a.value).then(c,e).then(g,b)}g(a.next())})};
var Realm=require("realm"),axios=require("axios"),UniversityCostSchema={name:"UniversityCost",properties:{universityTypeId:"int",universityType:"string",nonmedcost:"string",medcost:"string"}},KidsEducationCalc=function(){this.KidsEducationCalculatorRealm=new Realm({path:"kidsEducation.realm",schema:[UniversityCostSchema]});this.populateUniversityCost()};
KidsEducationCalc.prototype.populateUniversityCost=function(){var a=this;return $jscomp.executeAsyncGenerator(function(){function c(c,d,k){for(;;)switch(e){case 0:return e=1,{value:axios.get("http://isobardev.bambu.life:3000/api/Universityeducationcosts"),done:!1};case 1:if(1!=c){e=2;break}e=-1;throw k;case 2:b=g=d;f=b.data;if(!(-1<f.length)){e=3;break}a.KidsEducationCalculatorRealm.write(function(){a.KidsEducationCalculatorRealm["delete"](a.KidsEducationCalculatorRealm.objects("UniversityCost"));
for(var b=0;b<f.length;b++){var c=f[b];a.KidsEducationCalculatorRealm.create("UniversityCost",{universityTypeId:c.universityTypeId,universityType:c.universityType,nonmedcost:c.nonmedcost,medcost:c.medcost})}});e=-1;return{value:{response:{message:"Created"}},done:!0};case 3:e=-1;default:return{value:void 0,done:!0}}}var e=0,f,b,g,d={next:function(a){return c(0,a,void 0)},"throw":function(a){return c(1,void 0,a)},"return":function(a){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();
d[Symbol.iterator]=function(){return this};return d}())};KidsEducationCalc.prototype.getUniversityCost=function(){return this.KidsEducationCalculatorRealm.objects("UniversityCost").map(function(a){return Object.assign({},a)})};
KidsEducationCalc.prototype.universityCostCalculator=function(a){var c=a.age,e=a.universityId;a=a.medicine;if(35<c)return{response:{message:"age cannot be greater than 35"}};var f=18-c;c=24-c;e=this.KidsEducationCalculatorRealm.objects("UniversityCost").filtered("universityTypeId="+e).map(function(a){return Object.assign({},a)});if(!e)return{response:{message:"universityId invalid"}};if("yes"===a)var b=e[0].medcost;else"no"===a&&(b=e[0].nonmedcost);return{response:{goalYear:f,maxGoalYear:c,universityCost:b}}};
module.exports=KidsEducationCalc;